export const cars = [
    "Toyota", "Honda", "Ford", "Chevrolet", "Nissan", "Volkswagen", "BMW", "Mercedes-Benz", "Audi", "Hyundai",
    "Kia", "Mazda", "Subaru", "Lexus", "Dodge", "Ram", "Jeep", "GMC", "Cadillac", "Buick",
    "Chrysler", "Lincoln", "Volvo", "Jaguar", "Land Rover", "Porsche", "Tesla", "Fiat", "Alfa Romeo", "Maserati",
    "Ferrari", "Lamborghini", "Aston Martin", "Bentley", "Rolls-Royce", "McLaren", "Pagani", "Bugatti", "Acura", "Infiniti",
    "Genesis", "Mitsubishi", "Mini", "Suzuki", "Peugeot", "Citroen", "Renault", "Skoda", "Seat", "Saab",
    "Lancia", "Isuzu", "Daewoo", "Daihatsu", "Tata", "Mahindra", "Maruti Suzuki", "Proton", "Perodua", "Holden",
    "Opel", "Vauxhall", "Dacia", "Rover", "MG", "SsangYong", "Haval", "Great Wall", "Geely", "BYD",
    "Nio", "XPeng", "Lucid", "Rivian", "Fisker", "Faraday Future", "VinFast", "Wuling", "Baojun", "Chery",
    "JAC", "Zotye", "Lifan", "BAIC", "Changan", "GAC", "FAW", "Hongqi", "Noble", "Koenigsegg",
    "Spyker", "TVR", "Morgan", "Caterham", "Ariel", "Radical", "Ginetta", "BAC", "Wiesmann", "Ascari",
    "Mosler", "Vector", "Scion", "Eagle", "Plymouth", "Oldsmobile", "Saturn", "Pontiac", "Hummer", "Mercury",
    "Studebaker", "Packard", "DeSoto", "Hudson", "AMC", "International Harvester", "Checker", "Tucker", "Cord", "Auburn",
    "Edsel", "Franklin", "Graham", "Kaiser", "Willys", "Triumph", "Austin", "Morris", "Riley", "Singer",
    "Wolseley", "Hillman", "Sunbeam", "Talbot", "Simca", "Delahaye", "Humber", "Alvis", "Lagonda", "Bristol",
    "Jensen", "Marcos", "Panther", "Gilbern", "Cisitalia", "De Tomaso", "ISO", "Bizzarrini", "Siata", "Pininfarina",
    "Ghia", "Zagato", "Italdesign", "Bertone", "Michelotti", "Vignale", "Moretti", "Stanguellini", "Nardi", "OSCA",
    "Abarth", "ATS", "Autobianchi", "Innocenti", "Lamborghini", "Ferrari", "Maserati", "Pagani", "Alfa Romeo", "Fiat",
    "Lancia", "De Tomaso", "Isotta Fraschini", "Bizzarrini", "Cisitalia", "Fornasari", "Bugatti", "Peugeot", "Renault", "Citroen",
    "DS Automobiles", "Venturi", "Facel Vega", "Alpine", "Talbot-Lago", "Delahaye", "Panhard", "Matra", "Simca", "Aixam",
    "Ligier", "Microcar", "Mega", "Mia Electric", "Bellier", "Chatenet", "JDM", "Secma", "Renault", "Peugeot",
    "Citroen", "Opel", "Ford", "Volkswagen", "Audi", "BMW", "Mercedes-Benz", "Porsche", "Ferrari", "Lamborghini",
    "Maserati", "Aston Martin", "Bentley", "Rolls-Royce", "McLaren", "Pagani", "Bugatti", "Tesla", "Rivian", "Lucid",
    "Faraday Future", "Fisker", "Polestar", "Karma", "Nikola", "Aptera", "Lordstown", "Canoo", "Drako", "Bollinger",
    "Atlis", "Byton", "Faraday Future", "Fisker", "Lucid", "Nikola", "Polestar", "Rivian", "Tesla", "XPeng",
    "Aiways", "BYD", "Nio", "GAC", "Geely", "Chery", "Great Wall", "Haval", "Wuling", "Baojun",
    "Zotye", "JAC", "Lifan", "BAIC", "Changan", "FAW", "Hongqi", "Koenigsegg", "Spyker", "TVR",
    "Morgan", "Caterham", "Ariel", "Radical", "Ginetta", "BAC", "Wiesmann", "Ascari", "Mosler", "Vector",
    "Scion", "Eagle", "Plymouth", "Oldsmobile", "Saturn", "Pontiac", "Hummer", "Mercury", "Studebaker", "Packard",
    "DeSoto", "Hudson", "AMC", "International Harvester", "Checker", "Tucker", "Cord", "Auburn", "Edsel", "Franklin",
    "Graham", "Kaiser", "Willys", "Triumph", "Austin", "Morris", "Riley", "Singer", "Wolseley", "Hillman",
    "Sunbeam", "Talbot", "Simca", "Delahaye", "Humber", "Alvis", "Lagonda", "Bristol", "Jensen", "Marcos",
    "Panther", "Gilbern", "Cisitalia", "De Tomaso", "ISO", "Bizzarrini", "Siata", "Pininfarina", "Ghia", "Zagato",
    "Italdesign", "Bertone", "Michelotti", "Vignale", "Moretti", "Stanguellini", "Nardi", "OSCA", "Abarth", "ATS",
    "Autobianchi", "Innocenti", "Lamborghini", "Ferrari", "Maserati", "Pagani", "Alfa Romeo", "Fiat", "Lancia", "De Tomaso",
    "Isotta Fraschini"]